### ISSUE TITLE
Learn about continues integration(CI) and continues delivery(CD)

### ISSUE THREAD

**Issue by Chamindasl** [sumindaaa/smart-employee-service#6]
To finish the task, 
Do some research on what is CI/CD? what tools in the industry, 
Do less than 5 lines of writeup about cicd, as a comment

**Comment by sumindaaa** [comment]
Continuous integration helps to automate the deployment. further it ensure the latest version of the code available for all developers and users. delivering small chunks of code in small time periods  is called continuous delivery. it helps to reduce bugs, get a chance to test the project with an actual users.
Bamboo, GitLab, Team City are few tools used in the industry

**Comment by Chamindasl** [comment]
Good, But I was expecting you finish #5 first.

**Comment by Chamindasl** [comment]
> Continuous integration helps to automate the deployment. further it ensure the latest version of the code available for all developers and users. delivering small chunks of code in small time periods is called continuous delivery. it helps to reduce bugs, get a chance to test the project with an actual users.
> Bamboo, GitLab, Team City are few tools used in the industry

And I was not expecting copy-paste, in your own words makes more sense

**Comment by sumindaaa** [comment]
Hi, I didn't do any copy paste. those are my own words. Following are my references
https://stackify.com/continuous-delivery-vs-continuous-deployment-vs-continuous-integration/
https://www.katalon.com/resources-center/blog/ci-cd-tools/

**Comment by Chamindasl** [comment]
> Hi, I didn't do any copy paste. those are my own words.

Great. Do #5 then we can do some cool stuffs.

**Comment by sumindaaa** [comment]
i'm watching the java brains tutorial and will do soon
